language: python
python:
  - '3.6'
install:
  - pip install nose twine
script:
  - "./setup.py build sdist"
  - twine check dist/*
  - pip install .
  - nosetests
deploy:
  provider: pypi
  user: pfariello
  password:
    secure: Pjwf9dREkcWRvqcMiOn7a8+rxXZOWPy7CYWC8ilxUGeqTkMuvusbs8EQu0kO9Brs/0308GwHJNyAdBjxN5zAlO17cZF9q25qbweb+DqgJYCgXknvBFz2ZMyE5K7vTngP+KrHlj9/8nzg+OrNYMH27MmFCQuEpCRrI++3wl5UJdEi3SSzXQYNJ1usDCuM6GFCPMEQeF8Jz49t2WCLhZutxhXUkliGOE9XM/khCJHlp4Im+hzvJmvV4Hx3ZMu9KVNKS7i153c2eYKbZQCo18p2TcKw+XwYL6WkD5aFtKRiAaqsm37thLKR57+LbwMVGnTetIKSU+PVLuqXffTHtAOxYld7qbgxW1OE4y5UNoGR1QV3wBMWFmnQoI78FagyHDrh77Rmq8LxeQ5XTi1VCCZMefaFX3HedU8bJ7+sIWiDvIXXMB31zPwSZBmAX7z1jcDeWerGCFIValVPXQy3azrBjuXdybD6QrO79kIeVM3x+6cVMzmX2Ieej1n6jz3locOMXu5zWe4Z6xJgX7w72OMTlGpORjpmodztd9ahEf+EgZIhkbP2hTmuhhnPt25NghLrBefTtLwLXHOOGYiqv5F/Fpf6UWHsoq9wHdaB7NyfrT+Z1occCmKis0PXJIDFePUaSsDZz7cW61bJ1ZFN9JmnA6Lk3UruYBdN5O2HwrpW8ZU=
  on:
    tags: true
    python: '3.6'
  skip_existing: true
